# Generated by Django 5.0.3 on 2024-05-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_intro', '0004_employer_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/'),
        ),
    ]
