# Generated by Django 5.0.3 on 2024-05-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_intro', '0005_applicant_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/'),
        ),
    ]
